### ISSUE TITLE
<<DISCUSSION>> Bloomberg Issue

### ISSUE THREAD

**Issue by joony0123** [joony0123/LandmARk-Lens#11]
1. Only use OpenAPI Market data to get market data of the country(using geolocation)
https://www.bloomberglabs.com/api/documentation/

2. Get Demo version (30days trial) and use it for 30 days. But not sure if they will provide us to use apis too. 
https://www.bloomberg.com/professional/request-demo/?utm_source=bba-login&bbgsum=DG-WS-CORE-bba-login

Will Do : Definitely Bloomberg News for current events of that geolocation
https://newsapi.org/bloomberg-api

Any thoughts?

**Comment by ghost** [comment]
https://newsapi.org/bloomberg-api  Bloomberg API seems great! We can definitely use their free API sorted by country.

**Comment by sroyhong313** [comment]
Decide not to implement Bloomberg API. Closing issue.
