### ISSUE TITLE
Implement Bloomberg REST API

### ISSUE THREAD

**Issue by joshua31101** [joony0123/LandmARk-Lens#9]
https://www.bloomberglabs.com/api/

**Comment by sroyhong313** [comment]
@joshua31101 The Bloomberg api is to get market data. Getting news information costs money: https://www.bloomberg.com/professional/news/

Might have to rethink about using Bloomberg. If we are using it, then change its direction into getting market data?

**Comment by ghost** [comment]
@sroyhong313 Let's work on https://newsapi.org/bloomberg-api  since it offers free Bloomberg API and has "country" parameter so that we can get news based on user location.
